version: 2

models:
  - name: customer_order_summary
    columns:
      - name: name
        tests:
          - not_null
      - name: total_orders
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null
